name: Verify File Integrity

on: [push, pull_request]

jobs:
  verify_hashes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download CDN artifacts
        run: |
          set -euo pipefail
          curl -fsSL -o cdn_openpgp.min.js https://unpkg.com/openpgp@6.2.0/dist/openpgp.min.js
          # Tailwind CDN script (loader) served as JS from cdn.tailwindcss.com
          curl -fsSL -o cdn_tailwind.min.js https://cdn.tailwindcss.com/3.4.17

      - name: Compute SHA512 hashes
        run: |
          set -euo pipefail

          echo "::group::CDN hashes"
          sha512sum cdn_openpgp.min.js | tee cdn_openpgp.min.js.sha512
          sha512sum cdn_tailwind.min.js | tee cdn_tailwind.min.js.sha512
          echo "::endgroup::"

          echo "::group::Local file presence"
          test -f public/scripts/openpgp.min.js && echo "Found public/scripts/openpgp.min.js"
          test -f public/scripts/tailwind.min.js && echo "Found public/scripts/tailwind.min.js"
          echo "::endgroup::"

          echo "::group::Local hashes"
          sha512sum public/scripts/openpgp.min.js | tee local_openpgp.min.js.sha512
          sha512sum public/scripts/tailwind.min.js | tee local_tailwind.min.js.sha512
          echo "::endgroup::"

          # Export to env
          echo "CDN_HASH_OPENPGP=$(cut -d' ' -f1 cdn_openpgp.min.js.sha512)" >> $GITHUB_ENV
          echo "CDN_HASH_TAILWIND=$(cut -d' ' -f1 cdn_tailwind.min.js.sha512)" >> $GITHUB_ENV
          echo "LOCAL_HASH_OPENPGP=$(cut -d' ' -f1 local_openpgp.min.js.sha512)" >> $GITHUB_ENV
          echo "LOCAL_HASH_TAILWIND=$(cut -d' ' -f1 local_tailwind.min.js.sha512)" >> $GITHUB_ENV

      - name: Verify hashes
        run: |
          set -euo pipefail
          mismatch=0

          if [ "$LOCAL_HASH_OPENPGP" != "$CDN_HASH_OPENPGP" ]; then
            echo "::error title=openpgp.min.js hash mismatch::Expected $CDN_HASH_OPENPGP but found $LOCAL_HASH_OPENPGP"
            mismatch=1
          else
            echo "openpgp.min.js hash verified ✅"
          fi

          if [ "$LOCAL_HASH_TAILWIND" != "$CDN_HASH_TAILWIND" ]; then
            echo "::error title=tailwind.min.js hash mismatch::Expected $CDN_HASH_TAILWIND but found $LOCAL_HASH_TAILWIND"
            mismatch=1
          else
            echo "tailwind.min.js hash verified ✅"
          fi

          exit $mismatch
